<script lang="ts">
	import { untrack } from 'svelte';
	import { Button } from '$lib/components/ui/button';
	import { Input } from '$lib/components/ui/input';
	import { Label } from '$lib/components/ui/label';
	import { Switch } from '$lib/components/ui/switch';
	import * as Select from '$lib/components/ui/select';
	import * as Card from '$lib/components/ui/card';
	import FilesizeInput from '$lib/components/filesize-input.svelte';
	import { superForm, type SuperValidated } from 'sveltekit-superforms';
	import { zod4Client } from 'sveltekit-superforms/adapters';
	import { deviceSchema, type DeviceFormData } from '$lib/schemas/device';

	type Props = {
		data: SuperValidated<DeviceFormData>;
		submitLabel: string;
	};

	let { data, submitLabel }: Props = $props();

	// Initialize superform with client-side validation on blur
	// Using untrack to explicitly capture initial data (this is intentional for form libraries)
	const superFormResult = untrack(() =>
		superForm(data, {
			dataType: 'json',
			validators: zod4Client(deviceSchema),
			validationMethod: 'onblur'
		})
	);

	const { form, errors, message, enhance, submitting } = superFormResult;

	// Track if slug was auto-generated (to know when to stop auto-generating)
	let slugWasAutoGenerated = $state(untrack(() => !data.data.slug));

	// Auto-generate slug from name
	function generateSlug(name: string) {
		return name
			.toLowerCase()
			.replace(/[^a-z0-9]+/g, '-')
			.replace(/^-|-$/g, '');
	}

	function handleNameInput(e: Event) {
		const target = e.target as HTMLInputElement;
		$form.name = target.value;
		// Auto-generate slug only if user hasn't manually edited it
		const autoSlug = generateSlug(target.value);
		if (!$form.slug || slugWasAutoGenerated) {
			$form.slug = autoSlug;
			slugWasAutoGenerated = true;
		}
	}

	function handleSlugInput() {
		// User manually edited slug, stop auto-generating
		slugWasAutoGenerated = false;
	}

	const nsfwOptions = [
		{ value: '0', label: 'Accept All' },
		{ value: '1', label: 'SFW Only' },
		{ value: '2', label: 'NSFW Only' }
	];

	// Convert number to string for Select component, sync bidirectionally
	let nsfwValue = $state(($form.nsfw ?? 1).toString());

	// Sync nsfwValue back to form when changed
	$effect(() => {
		$form.nsfw = parseInt(nsfwValue, 10);
	});

	const nsfwLabel = $derived(nsfwOptions.find((o) => o.value === nsfwValue)?.label ?? 'SFW Only');
</script>

<form method="POST" use:enhance class="space-y-6">
	{#if $message}
		<div class="rounded-md bg-destructive/10 p-4 text-sm text-destructive">
			{$message}
		</div>
	{/if}

	<Card.Root>
		<Card.Header>
			<Card.Title>Basic Information</Card.Title>
		</Card.Header>
		<Card.Content class="space-y-4">
			<div class="flex items-center gap-4">
				<Switch bind:checked={$form.enabled} id="enabled" name="enabled" />
				<Label for="enabled">Enabled</Label>
			</div>

			<div class="grid gap-4 sm:grid-cols-2">
				<div class="space-y-2">
					<Label for="name">Name <span class="text-destructive">*</span></Label>
					<Input
						id="name"
						name="name"
						value={$form.name}
						oninput={handleNameInput}
						placeholder="My Desktop"
						aria-invalid={$errors.name ? 'true' : undefined}
					/>
					{#if $errors.name}
						<p class="text-xs text-destructive">{$errors.name}</p>
					{/if}
				</div>
				<div class="space-y-2">
					<Label for="slug">Slug <span class="text-destructive">*</span></Label>
					<Input
						id="slug"
						name="slug"
						bind:value={$form.slug}
						placeholder="my-desktop"
						aria-invalid={$errors.slug ? 'true' : undefined}
					/>
					<p class="text-xs text-muted-foreground">URL-friendly identifier for this device.</p>
					{#if $errors.slug}
						<p class="text-xs text-destructive">{$errors.slug}</p>
					{/if}
				</div>
			</div>
		</Card.Content>
	</Card.Root>

	<Card.Root>
		<Card.Header>
			<Card.Title>Display Settings</Card.Title>
			<Card.Description>Configure the target resolution and aspect ratio tolerance.</Card.Description>
		</Card.Header>
		<Card.Content class="space-y-4">
			<div class="grid gap-4 sm:grid-cols-2">
				<div class="space-y-2">
					<Label for="width">Width <span class="text-destructive">*</span></Label>
					<Input
						id="width"
						name="width"
						type="number"
						bind:value={$form.width}
						placeholder="1920"
						min="1"
						aria-invalid={$errors.width ? 'true' : undefined}
					/>
					{#if $errors.width}
						<p class="text-xs text-destructive">{$errors.width}</p>
					{/if}
				</div>
				<div class="space-y-2">
					<Label for="height">Height <span class="text-destructive">*</span></Label>
					<Input
						id="height"
						name="height"
						type="number"
						bind:value={$form.height}
						placeholder="1080"
						min="1"
						aria-invalid={$errors.height ? 'true' : undefined}
					/>
					{#if $errors.height}
						<p class="text-xs text-destructive">{$errors.height}</p>
					{/if}
				</div>
			</div>

			<div class="space-y-2">
				<Label for="aspectRatioDeviation">Aspect Ratio Deviation <span class="text-destructive">*</span></Label>
				<Input
					id="aspectRatioDeviation"
					name="aspectRatioDeviation"
					type="number"
					bind:value={$form.aspectRatioDeviation}
					placeholder="0.2"
					step="0.01"
					min="0"
					max="2"
					aria-invalid={$errors.aspectRatioDeviation ? 'true' : undefined}
				/>
				<p class="text-xs text-muted-foreground">
					Acceptable deviation from the target aspect ratio. E.g., 0.2 means +/- 0.2.
				</p>
				{#if $errors.aspectRatioDeviation}
					<p class="text-xs text-destructive">{$errors.aspectRatioDeviation}</p>
				{/if}
			</div>
		</Card.Content>
	</Card.Root>

	<Card.Root>
		<Card.Header>
			<Card.Title>Resolution Constraints</Card.Title>
			<Card.Description>Set minimum and maximum resolution limits (optional).</Card.Description>
		</Card.Header>
		<Card.Content class="space-y-4">
			<div class="grid gap-4 sm:grid-cols-2">
				<div class="space-y-2">
					<Label for="minWidth">Min Width</Label>
					<Input
						id="minWidth"
						name="minWidth"
						type="number"
						bind:value={$form.minWidth}
						placeholder="Optional"
						min="1"
						aria-invalid={$errors.minWidth ? 'true' : undefined}
					/>
					{#if $errors.minWidth}
						<p class="text-xs text-destructive">{$errors.minWidth}</p>
					{/if}
				</div>
				<div class="space-y-2">
					<Label for="maxWidth">Max Width</Label>
					<Input
						id="maxWidth"
						name="maxWidth"
						type="number"
						bind:value={$form.maxWidth}
						placeholder="Optional"
						min="1"
						aria-invalid={$errors.maxWidth ? 'true' : undefined}
					/>
					{#if $errors.maxWidth}
						<p class="text-xs text-destructive">{$errors.maxWidth}</p>
					{/if}
				</div>
			</div>
			<div class="grid gap-4 sm:grid-cols-2">
				<div class="space-y-2">
					<Label for="minHeight">Min Height</Label>
					<Input
						id="minHeight"
						name="minHeight"
						type="number"
						bind:value={$form.minHeight}
						placeholder="Optional"
						min="1"
						aria-invalid={$errors.minHeight ? 'true' : undefined}
					/>
					{#if $errors.minHeight}
						<p class="text-xs text-destructive">{$errors.minHeight}</p>
					{/if}
				</div>
				<div class="space-y-2">
					<Label for="maxHeight">Max Height</Label>
					<Input
						id="maxHeight"
						name="maxHeight"
						type="number"
						bind:value={$form.maxHeight}
						placeholder="Optional"
						min="1"
						aria-invalid={$errors.maxHeight ? 'true' : undefined}
					/>
					{#if $errors.maxHeight}
						<p class="text-xs text-destructive">{$errors.maxHeight}</p>
					{/if}
				</div>
			</div>
		</Card.Content>
	</Card.Root>

	<Card.Root>
		<Card.Header>
			<Card.Title>Filesize Constraints</Card.Title>
			<Card.Description>Set minimum and maximum filesize limits (optional).</Card.Description>
		</Card.Header>
		<Card.Content class="space-y-4">
			<div class="grid gap-4 sm:grid-cols-2">
				<div class="space-y-2">
					<Label for="minFilesize">Min Filesize</Label>
					<FilesizeInput
						id="minFilesize"
						name="minFilesize"
						value={$form.minFilesize}
						onchange={(v) => ($form.minFilesize = v)}
						aria-invalid={$errors.minFilesize ? 'true' : undefined}
					/>
					{#if $errors.minFilesize}
						<p class="text-xs text-destructive">{$errors.minFilesize}</p>
					{/if}
				</div>
				<div class="space-y-2">
					<Label for="maxFilesize">Max Filesize</Label>
					<FilesizeInput
						id="maxFilesize"
						name="maxFilesize"
						value={$form.maxFilesize}
						onchange={(v) => ($form.maxFilesize = v)}
						aria-invalid={$errors.maxFilesize ? 'true' : undefined}
					/>
					{#if $errors.maxFilesize}
						<p class="text-xs text-destructive">{$errors.maxFilesize}</p>
					{/if}
				</div>
			</div>
		</Card.Content>
	</Card.Root>

	<Card.Root>
		<Card.Header>
			<Card.Title>Content Filter</Card.Title>
		</Card.Header>
		<Card.Content>
			<div class="space-y-2">
				<Label>NSFW Filter</Label>
				<Select.Root type="single" bind:value={nsfwValue} name="nsfw">
					<Select.Trigger class="w-[200px]">
						{nsfwLabel}
					</Select.Trigger>
					<Select.Content>
						{#each nsfwOptions as option}
							<Select.Item value={option.value} label={option.label} />
						{/each}
					</Select.Content>
				</Select.Root>
				{#if $errors.nsfw}
					<p class="text-xs text-destructive">{$errors.nsfw}</p>
				{/if}
			</div>
		</Card.Content>
	</Card.Root>

	<div class="flex gap-4">
		<Button type="submit" disabled={$submitting}>
			{$submitting ? 'Saving...' : submitLabel}
		</Button>
		<Button type="button" variant="outline" href="/devices">Cancel</Button>
	</div>
</form>
